FROM debian:10

RUN set -eux; \
  apt-get update; \
  apt-get upgrade -y; \
  apt-get install -y postfix rsyslog procps; \
  rm -rf /var/lib/apt/lists/*

COPY main.cf /etc/postfix/main.cf
COPY run.sh /usr/local/bin/run.sh

EXPOSE 25
